package ProgramLab;
// Generated Nov 15, 2018 4:11:56 PM by Hibernate Tools 4.3.1


import java.awt.Color;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.Date;

/**
 * Polices generated by hbm2java
 */
public class Police  implements java.io.Serializable {


     private int id;
     private String name;
     private Date dob;
     private Integer posx;
     private Integer posy;
     private Integer speed;
     private Integer atk;
     private Integer color;
     private LocalDateTime timecreated;

    public Police() {
    }

	
    public Police(int id) {
        this.id = id;
    }
    public Police(int id, String name, Date dob, Integer posx, Integer posy, Integer speed, Integer atk, Integer color, LocalDateTime timecreated) {
       this.id = id;
       this.name = name;
       this.dob = dob;
       this.posx = posx;
       this.posy = posy;
       this.speed = speed;
       this.atk = atk;
       this.color = color;
       this.timecreated = timecreated;
    }
  
    public Police( String name, Date dob, Integer posx, Integer posy, Integer speed, Integer atk, Integer color) {
       this.name = name;
       this.dob = dob;
       this.posx = posx;
       this.posy = posy;
       this.speed = speed;
       this.atk = atk;
       this.color = color;
       
    }
    

    
    public Police( String name, Date dob, Integer posx, Integer posy, Integer speed, Integer atk, Integer color, Timestamp timecreated) {
       this.name = name;
       this.dob = dob;
       this.posx = posx;
       this.posy = posy;
       this.speed = speed;
       this.atk = atk;
       this.color = color;
       this.timecreated = timecreated.toLocalDateTime();
    }
    
    Police(String next, Date parse, String next0, String next1, int nextInt, int nextInt0, Color color) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public Integer getPosx() {
        return this.posx;
    }
    
    public void setPosx(Integer posx) {
        this.posx = posx;
    }
    public Integer getPosy() {
        return this.posy;
    }
    
    public void setPosy(Integer posy) {
        this.posy = posy;
    }
    public Integer getSpeed() {
        return this.speed;
    }
    
    public void setSpeed(Integer speed) {
        this.speed = speed;
    }
    public Integer getAtk() {
        return this.atk;
    }
    
    public void setAtk(Integer atk) {
        this.atk = atk;
    }
    public Integer getColor() {
        return this.color;
    }
    
    public void setColor(Integer color) {
        this.color = color;
    }
    public LocalDateTime getTimecreated() {
        return this.timecreated;
    }
    
    public void setTimecreated(Timestamp timecreated) {
        this.timecreated = timecreated.toLocalDateTime();
    }

    public void setTimecreated(LocalDateTime timecreated) {
        this.timecreated = timecreated;
    }
    
    int compareTo(Police o2) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String toString() {
        return "Police{" + "id=" + id + ", name=" + name + ", dob=" + dob + ", posx=" + posx + ", posy=" + posy + ", speed=" + speed + ", atk=" + atk + ", color=" + color + ", timecreated=" + timecreated + '}';
    }
    
}


